/*
  src/worker.js — the Aether Codex's server side.

  Everything the site needs to read is still static: index.html, the fonts,
  the service worker and the manifest are served from the repo root as
  static assets. This Worker adds three small endpoints on top, all backed
  by Workers AI (a free-tier account binding, no API key, nothing stored):

    POST /api/ask    { q, scope?, history?, mode?, depth? } -> SSE: sources, then the answer
    POST /api/quiz   { route, answer?, question? }          -> SSE: a question, or a grading
    POST /api/draft  { context }                            -> JSON: three drafted entries
    POST /api/embed  { texts[] }                            -> JSON: embedding vectors (for tools/embed.mjs)

  Retrieval is hybrid: BM25 over src/codex-index.json (generated by
  tools/build.js) fused by reciprocal rank with cosine similarity over
  src/codex-vectors.json (generated by tools/embed.mjs from the same index,
  using Workers AI's bge-small embedding model), so it needs no vector
  database. If the vectors are missing or stale the lexical half runs
  alone. The model only ever sees passages from the Codex and is told to
  cite them; the client turns every §, Eq. and code in the answer into a
  link. A per-IP limiter and a response cache keep a personal site inside
  the free daily allowance.
*/
import INDEX from "./codex-index.json";
import VEC from "./codex-vectors.json";

/* Candidate models, tried in order until one answers; Cloudflare retires
   model IDs from time to time, so the first working one is remembered per
   isolate and /api/models reports what this account can run today. */
const QUICK = [
  "@cf/meta/llama-3.1-8b-instruct-fast",
  "@cf/meta/llama-3.1-8b-instruct-fp8",
  "@cf/meta/llama-3.2-3b-instruct",
  "@cf/meta/llama-3.1-8b-instruct"
];
// "careful": the largest model the free tier will run, then progressively smaller ones
const CAREFUL = [
  "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
  "@cf/meta/llama-4-scout-17b-16e-instruct",
  "@cf/mistralai/mistral-small-3.1-24b-instruct",
  "@cf/qwen/qwen3-30b-a3b-fp8",
  "@cf/openai/gpt-oss-20b"
].concat(QUICK);
const MODELS = CAREFUL;
const EMBED_MODEL = "@cf/baai/bge-small-en-v1.5";
const MODEL_OF = { quick: QUICK[0], careful: CAREFUL[0] };
let MODEL = MODEL_OF.careful;
// a model that is gone (retired ID) is skipped for the rest of the isolate's life; one
// that is merely busy is skipped for this request only, so the next one tries it again
function retired(e) { const m = String(e && e.message || e); return /deprecat|not found|no such model|5028|5007|does not exist|unsupported/i.test(m); }
function busy(e) { const m = String(e && e.message || e); return /capacity|overload|timed? ?out|3040|3036|unavailable|too many|rate/i.test(m); }
const GONE = new Set();
async function runAI(env, opts, depth) {
  const tier = depth === "quick" ? "quick" : "careful";
  const list = (tier === "quick" ? QUICK : CAREFUL).filter((m) => !GONE.has(m));
  const start = Math.max(0, list.indexOf(MODEL_OF[tier]));
  const order = list.slice(start).concat(list.slice(0, start));
  let last = null;
  for (const m of order) {
    try { const out = await env.AI.run(m, opts); MODEL = m; return out; }
    catch (e) { last = e; if (retired(e)) GONE.add(m); else if (!busy(e)) throw e; }
  }
  throw last || new Error("no model available");
}
const MAX_TOKENS = 700;
const RATE = { windowMs: 10 * 60 * 1000, max: 24 }; // per IP, per isolate
const hits = new Map();

/* ───────── BM25 over the chunks ───────── */
const STOP = new Set("the a an and or of to in on at for is are was were be been by with as it its this that these those from into than then so if not no nor but which who whom what when where why how all any each such only also very can could would should may might will shall do does did done has have had having i you he she we they them their our your his her my me us".split(" "));
function tokens(s) {
  return (s.toLowerCase().match(/[a-z0-9_§.]+/g) || []).map((t) => t.replace(/^[§.]+|[.]+$/g, "")).filter((t) => t.length > 1 && !STOP.has(t));
}
let IDX = null;
function buildIndex() {
  const docs = INDEX.chunks.map((c) => { const toks = tokens(c.t + " " + c.t + " " + c.x); const tf = new Map(); toks.forEach((t) => tf.set(t, (tf.get(t) || 0) + 1)); return { c, tf, len: toks.length }; });
  const df = new Map(); docs.forEach((d) => d.tf.forEach((_, t) => df.set(t, (df.get(t) || 0) + 1)));
  const avg = docs.reduce((s, d) => s + d.len, 0) / docs.length;
  IDX = { docs, df, avg, N: docs.length };
}
function search(q, scope, k) { return bm25Ranked(q, scope, k); }
/* ───────── semantic half: cosine over int8 vectors, fused with BM25 by reciprocal rank ───────── */
let VECS = null;
function vectorsReady() {
  if (VECS !== null) return VECS !== false;
  if (!VEC || !VEC.n || VEC.n !== INDEX.chunks.length || VEC.hash !== INDEX.hash || !VEC.q) { VECS = false; return false; }
  try { const bin = atob(VEC.q); const a = new Int8Array(bin.length); for (let i = 0; i < bin.length; i++) a[i] = (bin.charCodeAt(i) << 24) >> 24; VECS = { a, d: VEC.dims }; return true; }
  catch (e) { VECS = false; return false; }
}
async function embed(env, text) {
  const out = await env.AI.run(EMBED_MODEL, { text: [text.slice(0, 2000)] });
  const v = out && out.data && out.data[0]; if (!v) throw new Error("no embedding");
  let n = 0; for (const x of v) n += x * x; n = Math.sqrt(n) || 1;
  return Float32Array.from(v, (x) => x / n);
}
function bm25Ranked(q, scope, k) {
  if (!IDX) buildIndex();
  const qt = Array.from(new Set(tokens(q)));
  const k1 = 1.4, b = 0.75;
  const codes = q.match(/\b[A-Z]{1,2}(?:-[A-Z]{2})?-\d{2,3}\b/g) || [];
  const eqs = q.match(/\b\d\.\d+[a-g]?\b/g) || [];
  const scored = [];
  for (const d of IDX.docs) {
    if (scope && d.c.r !== scope && !(scope === "directory" && d.c.k === "spell")) continue;
    let s = 0;
    for (const t of qt) {
      const f = d.tf.get(t); if (!f) continue;
      const n = IDX.df.get(t) || 0;
      const idf = Math.log(1 + (IDX.N - n + 0.5) / (n + 0.5));
      s += idf * (f * (k1 + 1)) / (f + k1 * (1 - b + b * d.len / IDX.avg));
    }
    // exact code / equation mentions are strong signals
    if (codes.some((c) => d.c.id === c)) s += 8;
    if (d.c.k === "eq" && eqs.some((e) => d.c.id === "eq-" + e.replace(/\./g, "-"))) s += 8;
    if (s > 0) scored.push({ s, d });
  }
  scored.sort((a, b) => b.s - a.s);
  return scored.slice(0, k).map((x) => x.d.c);
}
async function searchHybrid(env, q, scope, k) {
  const lex = bm25Ranked(q, scope, 30);
  if (!vectorsReady() || !env || !env.AI) return lex.slice(0, k);
  let qv;
  try { qv = await embed(env, q); } catch (e) { return lex.slice(0, k); }
  const { a, d } = VECS;
  const sem = [];
  for (let i = 0; i < INDEX.chunks.length; i++) {
    const c = INDEX.chunks[i];
    if (scope && c.r !== scope && !(scope === "directory" && c.k === "spell")) continue;
    let dot = 0; const o = i * d;
    for (let j = 0; j < d; j++) dot += a[o + j] * qv[j];
    sem.push({ s: dot, c });
  }
  sem.sort((x, y) => y.s - x.s);
  const fused = new Map();
  const add = (list, w) => list.forEach((c, r) => { const e = fused.get(c) || { c, s: 0 }; e.s += w / (60 + r); fused.set(c, e); });
  add(lex, 1); add(sem.slice(0, 30).map((x) => x.c), 1);
  // an exact code or equation mention is always kept
  lex.slice(0, 2).forEach((c) => { const e = fused.get(c); if (/^(spell|eq)$/.test(c.k) && new RegExp("\\b" + c.id.replace(/^eq-/, "").replace(/-/g, "\\.") + "\\b").test(q)) e.s += 1; });
  return Array.from(fused.values()).sort((x, y) => y.s - x.s).slice(0, k).map((x) => x.c);
}
function cite(c) {
  if (c.k === "spell") return c.id;
  if (c.k === "eq") return "Eq. " + c.id.replace(/^eq-/, "").replace(/-/g, ".");
  if (c.k === "sym") return c.t;
  const m = c.id.match(/^sec-(\d+(?:-\d+)?)/);
  return m ? "§" + m[1].replace(/-/g, ".") : c.t;
}
function sourceOut(c) { return { k: c.k, r: c.r, id: c.id, t: c.t, page: c.page, cite: cite(c) }; }

/* ───────── prompts ───────── */
const SYSTEM = `You are the study tutor for the Aether Codex, a fictional hard-magic system written as physics. You answer only from the passages provided, which are the Codex's own text. Rules:
- The Codex is fiction; treat its equations and rules as the facts of that world, and never claim they are real physics. If a passage draws an analogy to real physics, you may explain the analogy.
- Cite as you go, inline, using the Codex's own numbering exactly as it appears in the passages: section numbers like §3.5, equation numbers like Eq. 4.7, and Directory codes like N-EM-01. Every claim should be traceable to a citation.
- Write plainly, in short paragraphs, for someone learning the system. Prefer a worked example over an abstraction. Do not use headings, bullet lists, markdown tables or emoji; you may use *italics* and \`code\` for symbols.
- Symbols are written in the Codex's plain ASCII (Fid, k_f, Xi(Ae, g), dAe); use them exactly.
- If the passages do not answer the question, say so in one sentence and point to the nearest relevant section rather than inventing anything.
- Keep answers under 300 words unless the question needs a derivation.`;

const MODES = {
  explain: "",
  socratic: "\nMode: Socratic. Do not answer directly. First ask the student one pointed question that would lead them to the answer themselves, citing the passage it is drawn from; then, under the words 'If you are stuck:', give a two-sentence hint and the section to reread. Give the full answer only if the student's message says they give up or asks you to answer outright.",
  derive: "\nMode: Derivation. Take the equation or rule the question is about and walk it term by term: state it as the Codex writes it, then for each term say what it is, where it is defined, and what happens to the result when it grows or shrinks; end with one worked example with plausible numbers, clearly marked as an illustration. Cite each step.",
  compare: "\nMode: Comparison. Set the two things the question names side by side: what they share, where they differ, and the rule that decides which applies. Where possible, show the difference through one concrete situation. Cite the section for each side.",
  story: "\nMode: In the story. Describe what a witness would see, hear and feel if this were happening in front of them, in prose a novelist could use, but stay strictly inside the rules: every visible detail must follow from a cited rule, and say in one closing sentence which rules the scene rests on."
};
const QUIZ_ASK = `You are the study tutor for the Aether Codex, a fictional hard-magic system written as physics. From the passages, write ONE examination question that tests understanding of the mechanism (why, not what), the kind a good textbook puts at the end of a chapter. It must be answerable from the passages alone and take two to five sentences to answer. Output only the question, with no preamble, and end it with the citation of the section it comes from in parentheses, e.g. (§3.5).`;

const QUIZ_GRADE = `You are the study tutor for the Aether Codex, a fictional hard-magic system written as physics. You are given a question, the student's answer, and the relevant passages. Grade the answer against the passages: first a verdict word on its own line, one of "Correct.", "Partly correct." or "Not yet.", then two to five sentences saying what was right, what was missing or wrong, and the ideal answer, citing sections, equations and codes inline exactly as they appear in the passages (§3.5, Eq. 4.7, N-EM-01). Be specific and kind. No headings or lists.`;

const DRAFT = `You write entries for the Spell Directory of the Aether Codex, a fictional hard-magic system. You are given the mechanics of a working (its tier, equation, numbers and variation) and several existing Directory entries as examples of the house voice: dry, precise, worldly, one paragraph, naming who uses the technique and what it pointedly does not do, citing equations by number (Eq. 4.0a) and related entries by code (N-EM-02). Write THREE new entries for the working described, each with a distinct name and a distinct use (a trade, a watch or military use, a domestic or ceremonial use). Names are two or three words, evocative, never generic. Each entry is 50 to 90 words and must be consistent with the mechanics given: the same equation, the same direction, the same tier. Never invent new equation numbers. Output strictly as JSON: {"drafts":[{"name":"...","text":"..."},{"name":"...","text":"..."},{"name":"...","text":"..."}]} and nothing else.`;

/* ───────── helpers ───────── */
function json(obj, status, extra) { return new Response(JSON.stringify(obj), { status: status || 200, headers: Object.assign({ "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }, extra || {}) }); }
function limited(request) {
  const ip = request.headers.get("cf-connecting-ip") || "anon";
  const now = Date.now();
  let h = hits.get(ip); if (!h || now - h.t0 > RATE.windowMs) { h = { t0: now, n: 0 }; hits.set(ip, h); }
  h.n++;
  if (hits.size > 5000) hits.clear();
  return h.n > RATE.max;
}
function passagesBlock(cs) { return cs.map((c, i) => "[" + (i + 1) + "] (" + cite(c) + " · " + c.t + ")\n" + c.x.slice(0, 1800)).join("\n\n"); }
async function sha(s) { const b = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s)); return Array.from(new Uint8Array(b)).slice(0, 16).map((x) => x.toString(16).padStart(2, "0")).join(""); }

/* SSE: a "sources" event first, then the model's stream, relayed as-is. */
async function streamWithSources(env, ctx, messages, sources, cacheKey, depth) {
  const cache = (typeof caches !== "undefined" && caches.default) ? caches.default : null;
  if (cacheKey && cache) { try { const hit = await cache.match(cacheKey); if (hit) { const h = new Headers(hit.headers); h.set("x-aether-cache", "hit"); return new Response(hit.body, { headers: h }); } } catch (e) { /* cache is best-effort */ } }
  const ai = await runAI(env, { messages, stream: true, max_tokens: depth === "quick" ? MAX_TOKENS : 900, temperature: 0.3 }, depth || "careful");
  const enc = new TextEncoder();
  const head = enc.encode("event: sources\ndata: " + JSON.stringify(sources.map(sourceOut)) + "\n\n");
  const { readable, writable } = new TransformStream();
  const w = writable.getWriter();
  ctx.waitUntil((async () => {
    await w.write(head);
    // normalise the model's SSE: some models emit numeric tokens as JSON numbers
    // and some wrap text differently; the client always gets {"response": "<string>"}
    const reader = ai.getReader(), dec = new TextDecoder();
    let buf = "";
    const emit = async (block) => {
      const lines = block.split("\n").filter((l) => l.startsWith("data:"));
      for (const l of lines) {
        const d = l.slice(5).trim();
        if (!d || d === "[DONE]") continue;
        let piece = "";
        try { const j = JSON.parse(d); piece = j.response != null ? String(j.response) : (j.choices && j.choices[0] && j.choices[0].delta && j.choices[0].delta.content) || ""; } catch (e) { piece = ""; }
        if (piece) await w.write(enc.encode("data: " + JSON.stringify({ response: piece }) + "\n\n"));
      }
    };
    for (;;) {
      const { value, done } = await reader.read(); if (done) break;
      buf += dec.decode(value, { stream: true });
      let i; while ((i = buf.indexOf("\n\n")) >= 0) { await emit(buf.slice(0, i)); buf = buf.slice(i + 2); }
    }
    if (buf.trim()) await emit(buf);
    await w.write(enc.encode("event: done\ndata: {}\n\n"));
    await w.close();
  })());
  const headers = { "content-type": "text/event-stream; charset=utf-8", "cache-control": "no-store", "x-accel-buffering": "no" };
  if (cacheKey && cache) {
    const [a, b] = readable.tee();
    ctx.waitUntil(cache.put(cacheKey, new Response(b, { headers: Object.assign({}, headers, { "cache-control": "public, max-age=86400" }) })).catch(() => {}));
    return new Response(a, { headers });
  }
  return new Response(readable, { headers });
}

/* ───────── endpoints ───────── */
async function ask(request, env, ctx) {
  const body = await request.json().catch(() => ({}));
  const q = String(body.q || "").trim().slice(0, 600);
  const scope = typeof body.scope === "string" ? body.scope.slice(0, 40) : "";
  const history = Array.isArray(body.history) ? body.history.slice(-4).map((m) => ({ role: m.role === "assistant" ? "assistant" : "user", content: String(m.content || "").slice(0, 1200) })) : [];
  const mode = MODES[body.mode] !== undefined ? body.mode : "explain";
  const depth = body.depth === "quick" ? "quick" : "careful";
  if (!q) return json({ error: "Ask something." }, 400);
  const sources = await searchHybrid(env, q + " " + history.map((m) => m.content).join(" ").slice(0, 300), scope, mode === "compare" ? 8 : 6);
  if (!sources.length) return json({ error: "Nothing in the Codex matches that. Try naming a section, an equation or a spell code." }, 404);
  const messages = [{ role: "system", content: SYSTEM + MODES[mode] }, { role: "user", content: "Passages from the Codex:\n\n" + passagesBlock(sources) }].concat(history, [{ role: "user", content: q }]);
  const key = history.length ? null : new Request("https://cache.aether/ask/" + INDEX.version + "/" + (await sha(scope + "|" + mode + "|" + depth + "|" + q.toLowerCase())));
  return streamWithSources(env, ctx, messages, sources, key, depth);
}
async function quiz(request, env, ctx) {
  const body = await request.json().catch(() => ({}));
  const route = String(body.route || "foundations").slice(0, 40);
  const question = String(body.question || "").slice(0, 1200);
  const answer = String(body.answer || "").slice(0, 2000);
  if (question && answer) {
    const sources = await searchHybrid(env, question + " " + answer, route, 6);
    const messages = [{ role: "system", content: QUIZ_GRADE }, { role: "user", content: "Passages:\n\n" + passagesBlock(sources) + "\n\nQuestion: " + question + "\n\nStudent's answer: " + answer }];
    return streamWithSources(env, ctx, messages, sources, null);
  }
  // a fresh question: pick a random substantial section of the chapter
  const pool = INDEX.chunks.filter((c) => c.k === "sec" && c.r === route && c.x.length > 600);
  if (!pool.length) return json({ error: "No chapter by that name." }, 404);
  const seed = Number(body.seed) || Math.floor(Math.random() * 1e6);
  const pick = pool[seed % pool.length];
  const sources = [pick].concat(search(pick.t, route, 3).filter((c) => c !== pick).slice(0, 2));
  const messages = [{ role: "system", content: QUIZ_ASK }, { role: "user", content: "Passages:\n\n" + passagesBlock(sources) }];
  return streamWithSources(env, ctx, messages, sources, null);
}
async function draft(request, env) {
  const body = await request.json().catch(() => ({}));
  const c = body.context || {};
  const desc = String(c.description || "").slice(0, 1500);
  if (!desc) return json({ error: "No working described." }, 400);
  const examples = Array.isArray(c.examples) ? c.examples.slice(0, 5).map((e) => String(e).slice(0, 600)) : [];
  const sources = search(desc, "", 4).filter((s) => s.k === "spell");
  const shots = examples.length ? examples : sources.map((s) => s.x);
  const messages = [{ role: "system", content: DRAFT }, { role: "user", content: "Existing entries, for voice:\n\n" + shots.join("\n\n") + "\n\nThe working to write entries for:\n" + desc + "\n\nOutput the JSON now." }];
  const out = await runAI(env, { messages, max_tokens: 900, temperature: 0.8 }, "quick");
  const text = typeof out === "string" ? out : (out && typeof out.response === "string") ? out.response : JSON.stringify((out && out.response != null) ? out.response : out);
  const m = text.match(/\{[\s\S]*\}/);
  let drafts = [];
  try {
    const parsed = JSON.parse(m ? m[0] : text);
    drafts = (parsed.drafts || []).filter((d) => d && d.name && d.text).slice(0, 3).map((d) => {
      const name = String(d.name).replace(/^\[?[A-Z]{1,2}(?:-[A-Z]{2})?-\d+\]?\s*/, "").slice(0, 60).trim();
      // the model tends to copy the examples' "[CODE] Name (Tier, Force)." prefix; the sheet adds its own
      let body = String(d.text).trim().replace(/^\[?[A-Z]{1,2}(?:-[A-Z]{2})?-\d+\]?\s*/, "");
      if (body.toLowerCase().indexOf(name.toLowerCase()) === 0) body = body.slice(name.length).replace(/^\s*\([^)]*\)\s*[.:—-]?\s*/, "").replace(/^\s*[.:—-]\s*/, "");
      return { name, text: body.charAt(0).toUpperCase() + body.slice(1, 900) };
    });
  } catch (e) { /* fall through */ }
  if (!drafts.length) return json({ error: "The model did not return usable drafts; try again." }, 502);
  return json({ drafts, model: MODEL, examples: sources.map(sourceOut) });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/api/")) {
      if (request.method === "OPTIONS") return new Response(null, { status: 204 });
      if (request.method !== "POST") return json({ error: "POST only." }, 405);
      if (!env.AI) return json({ error: "Workers AI is not bound on this deployment." }, 503);
      if (limited(request)) return json({ error: "Slow down a little: the free tier allows a few dozen questions per ten minutes." }, 429, { "retry-after": "600" });
      try {
        if (url.pathname === "/api/ask") return await ask(request, env, ctx);
        if (url.pathname === "/api/quiz") return await quiz(request, env, ctx);
        if (url.pathname === "/api/draft") return await draft(request, env);
        if (url.pathname === "/api/embed") {
          const body = await request.json().catch(() => ({}));
          const texts = Array.isArray(body.texts) ? body.texts.slice(0, 64).map((t) => String(t).slice(0, 2500)) : [];
          if (!texts.length) return json({ error: "Send { texts: [...] }." }, 400);
          const out = await env.AI.run(EMBED_MODEL, { text: texts });
          return json({ model: EMBED_MODEL, dims: out.data && out.data[0] ? out.data[0].length : 0, vectors: out.data || [] });
        }
        if (url.pathname === "/api/health") return json({ ok: true, chunks: INDEX.chunks.length, version: INDEX.version, index: INDEX.hash, vectors: vectorsReady() ? { model: VEC.model, dims: VEC.dims, n: VEC.n } : null, models: MODEL_OF, model: MODEL });
        if (url.pathname === "/api/models") {
          const report = [];
          for (const m of MODELS) { try { const out = await env.AI.run(m, { messages: [{ role: "user", content: "Reply with the single word: ready" }], max_tokens: 4 }); report.push({ model: m, ok: true, reply: String((out && out.response) || "").slice(0, 20) }); } catch (e) { report.push({ model: m, ok: false, error: String(e && e.message || e).slice(0, 100) }); } }
          return json({ current: MODEL, report });
        }
      } catch (e) {
        return json({ error: "The model is unavailable right now (" + (e && e.message ? e.message.slice(0, 120) : "unknown") + "). The daily free allowance may be used up; try again later." }, 503);
      }
      return json({ error: "No such endpoint." }, 404);
    }
    return env.ASSETS.fetch(request);
  }
};
